### ISSUE TITLE
Unhandled Rejection

### ISSUE THREAD

**Issue by stavrosdidakis** [rarcega/instagram-scraper-node#1]
I receive this error:
Unhandled rejection TypeError: expecting an array or an iterable object but got [object Null]
    at apiRejection

Any idea why is this happening?
Thanks

**Comment by itsacezon** [comment]
This might happen if the item you're trying to download is from a carousel. I tried rectifying this through my fork: https://github.com/itsacezon/instagram-scraper-node/blob/master/lib/scraper.js
